[2025-03-01T13:30:46.542+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-01T13:30:46.580+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_thegioididong_daily.run_spider_task manual__2025-03-01T13:30:44.928233+00:00 [queued]>
[2025-03-01T13:30:46.590+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_thegioididong_daily.run_spider_task manual__2025-03-01T13:30:44.928233+00:00 [queued]>
[2025-03-01T13:30:46.591+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-03-01T13:30:46.612+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spider_task> on 2025-03-01 13:30:44.928233+00:00
[2025-03-01T13:30:46.622+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-01T13:30:46.626+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'crawl_thegioididong_daily', 'run_spider_task', 'manual__2025-03-01T13:30:44.928233+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/crawl_daily_tgdd.py', '--cfg-path', '/tmp/tmpv7fo5xqc']
[2025-03-01T13:30:46.629+0000] {standard_task_runner.py:64} INFO - Started process 104 to run task
[2025-03-01T13:30:46.629+0000] {standard_task_runner.py:91} INFO - Job 103: Subtask run_spider_task
[2025-03-01T13:30:46.707+0000] {task_command.py:426} INFO - Running <TaskInstance: crawl_thegioididong_daily.run_spider_task manual__2025-03-01T13:30:44.928233+00:00 [running]> on host 934a1bc80592
[2025-03-01T13:30:46.837+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawl_thegioididong_daily' AIRFLOW_CTX_TASK_ID='run_spider_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T13:30:44.928233+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-01T13:30:44.928233+00:00'
[2025-03-01T13:30:46.839+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-01T13:30:46.871+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-01T13:30:46.872+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/crawler/tgdd_crawler/tgdd_crawler; scrapy crawl my_spider -a daily=true; ']
[2025-03-01T13:30:46.889+0000] {subprocess.py:86} INFO - Output:
[2025-03-01T13:30:46.917+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: scrapy: command not found
[2025-03-01T13:30:46.917+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-03-01T13:30:46.918+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-01T13:30:46.936+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-01T13:30:46.944+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=crawl_thegioididong_daily, task_id=run_spider_task, run_id=manual__2025-03-01T13:30:44.928233+00:00, execution_date=20250301T133044, start_date=20250301T133046, end_date=20250301T133046
[2025-03-01T13:30:46.970+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 103 for task run_spider_task (Bash command failed. The command returned a non-zero exit code 127.; 104)
[2025-03-01T13:30:47.007+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-01T13:30:47.045+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-01T13:30:47.053+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
