[2025-03-05T16:41:13.417+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-05T16:41:13.452+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_thegioididong_daily.crawl manual__2025-03-05T16:41:11.490444+00:00 [queued]>
[2025-03-05T16:41:13.464+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_thegioididong_daily.crawl manual__2025-03-05T16:41:11.490444+00:00 [queued]>
[2025-03-05T16:41:13.465+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-03-05T16:41:13.482+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): crawl> on 2025-03-05 16:41:11.490444+00:00
[2025-03-05T16:41:13.488+0000] {standard_task_runner.py:64} INFO - Started process 122 to run task
[2025-03-05T16:41:13.491+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'crawl_thegioididong_daily', 'crawl', 'manual__2025-03-05T16:41:11.490444+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/crawl_daily_tgdd.py', '--cfg-path', '/tmp/tmp35giynvg']
[2025-03-05T16:41:13.494+0000] {standard_task_runner.py:91} INFO - Job 276: Subtask crawl
[2025-03-05T16:41:13.566+0000] {task_command.py:426} INFO - Running <TaskInstance: crawl_thegioididong_daily.crawl manual__2025-03-05T16:41:11.490444+00:00 [running]> on host 2ea7787db707
[2025-03-05T16:41:13.680+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawl_thegioididong_daily' AIRFLOW_CTX_TASK_ID='crawl' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T16:41:11.490444+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T16:41:11.490444+00:00'
[2025-03-05T16:41:13.682+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-05T16:41:13.718+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-05T16:41:13.719+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd crawler/tgdd_crawler/tgdd_crawler; scrapy crawl tgdd_crawler -a daily=true; ']
[2025-03-05T16:41:13.732+0000] {subprocess.py:86} INFO - Output:
[2025-03-05T16:41:13.733+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: crawler/tgdd_crawler/tgdd_crawler: No such file or directory
[2025-03-05T16:41:15.343+0000] {subprocess.py:93} INFO - Scrapy 2.12.0 - no active project
[2025-03-05T16:41:15.344+0000] {subprocess.py:93} INFO - 
[2025-03-05T16:41:15.345+0000] {subprocess.py:93} INFO - Unknown command: crawl
[2025-03-05T16:41:15.346+0000] {subprocess.py:93} INFO - 
[2025-03-05T16:41:15.346+0000] {subprocess.py:93} INFO - Use "scrapy" to see available commands
[2025-03-05T16:41:15.481+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-03-05T16:41:15.483+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-05T16:41:15.501+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-03-05T16:41:15.506+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=crawl_thegioididong_daily, task_id=crawl, run_id=manual__2025-03-05T16:41:11.490444+00:00, execution_date=20250305T164111, start_date=20250305T164113, end_date=20250305T164115
[2025-03-05T16:41:15.524+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 276 for task crawl (Bash command failed. The command returned a non-zero exit code 2.; 122)
[2025-03-05T16:41:15.543+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-05T16:41:15.567+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-05T16:41:15.575+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
