[2025-03-01T16:51:15.608+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-01T16:51:15.643+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crawl_thegioididong_daily.crawl manual__2025-03-01T16:51:14.053055+00:00 [queued]>
[2025-03-01T16:51:15.655+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crawl_thegioididong_daily.crawl manual__2025-03-01T16:51:14.053055+00:00 [queued]>
[2025-03-01T16:51:15.656+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-03-01T16:51:15.672+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): crawl> on 2025-03-01 16:51:14.053055+00:00
[2025-03-01T16:51:15.679+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=148) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-01T16:51:15.680+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'crawl_thegioididong_daily', 'crawl', 'manual__2025-03-01T16:51:14.053055+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/crawl_daily_tgdd.py', '--cfg-path', '/tmp/tmp6hfrcjvy']
[2025-03-01T16:51:15.681+0000] {standard_task_runner.py:64} INFO - Started process 149 to run task
[2025-03-01T16:51:15.681+0000] {standard_task_runner.py:91} INFO - Job 162: Subtask crawl
[2025-03-01T16:51:15.731+0000] {task_command.py:426} INFO - Running <TaskInstance: crawl_thegioididong_daily.crawl manual__2025-03-01T16:51:14.053055+00:00 [running]> on host d6b41eaa664f
[2025-03-01T16:51:15.817+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crawl_thegioididong_daily' AIRFLOW_CTX_TASK_ID='crawl' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T16:51:14.053055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-01T16:51:14.053055+00:00'
[2025-03-01T16:51:15.819+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-01T16:51:15.837+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-01T16:51:15.839+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/crawler/tgdd_crawler/tgdd_crawler; scrapy crawl tgdd_crawler -a daily=true; ']
[2025-03-01T16:51:15.847+0000] {subprocess.py:86} INFO - Output:
[2025-03-01T16:51:15.850+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /opt/***/crawler/tgdd_crawler/tgdd_crawler: No such file or directory
[2025-03-01T16:51:15.852+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: scrapy: command not found
[2025-03-01T16:51:15.852+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-03-01T16:51:15.853+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-01T16:51:15.862+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-03-01T16:51:15.868+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=crawl_thegioididong_daily, task_id=crawl, run_id=manual__2025-03-01T16:51:14.053055+00:00, execution_date=20250301T165114, start_date=20250301T165115, end_date=20250301T165115
[2025-03-01T16:51:15.880+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 162 for task crawl (Bash command failed. The command returned a non-zero exit code 127.; 149)
[2025-03-01T16:51:15.896+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-01T16:51:15.915+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-01T16:51:15.920+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
